# Generated by Django 4.2.7 on 2023-11-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OmahaEvent',
            fields=[
                ('omaha_event_id', models.IntegerField(primary_key=True, serialize=False)),
                ('omaha_event_title', models.CharField(max_length=255)),
                ('omaha_event_url', models.TextField()),
                ('omaha_event_description', models.CharField(max_length=150)),
                ('event_image', models.ImageField(blank=True, null=True, upload_to='event_images/')),
            ],
        ),
    ]
