# Generated by Django 4.2.7 on 2023-11-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('photo', models.ImageField(upload_to='owner/')),
                ('office_address', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=254)),
            ],
        ),
    ]
