# Generated by Django 4.2.7 on 2023-11-29 16:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0002_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyNeighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyPriceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_range_span', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('street', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=60)),
                ('zipcode', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('sold', 'Sold')], default='available', max_length=10)),
                ('featured', models.BooleanField(default=False)),
                ('photo1', models.ImageField(upload_to='listing_images/')),
                ('photo2', models.ImageField(blank=True, upload_to='listing_images/')),
                ('photo3', models.ImageField(blank=True, upload_to='listing_images/')),
                ('photo4', models.ImageField(blank=True, upload_to='listing_images/')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RealEstate.propertyneighborhood')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RealEstate.owner')),
                ('price_range', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RealEstate.propertypricerange')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='RealEstate.propertytype')),
            ],
        ),
    ]
