# Generated by Django 4.2.7 on 2023-11-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstate', '0003_propertyneighborhood_propertypricerange_propertytype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylisting',
            name='name',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
